baseURL = "https://wslhub.com/"
languageCode = "ko-kr"
title = "W$L/hub>_"
description = "한국 WSL 사용자 그룹은 국내 WSL(Windows Subsystem for Linux) 및 Linux 사용자를 위한 커뮤니티 입니다."
theme = "kube"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "WSLHUB" # add your company name
  github = "https://github.com/wslhub" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""
[[menu.main]]
    name = "WSL 시작하기"
    weight = -150
    url = "https://wslhub.com/wsl-firststep"
[[menu.main]]
    name = "WSLHUB on Medium"
    weight = -100
    url = "https://medium.com/wslhub"
[[menu.main]]
    name = "Blog"
    weight = -50
    url = "/blog/"